### ISSUE TITLE
Placing Third-party Service

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb_site_configuration#47]
I'm concerned that the tools for placing third-party services don't have the flexibility needed by our users.

Case in point, the registrar's office has 2 chat widgets they run on their site - one that runs on 15 pages (including the homepage) and one that runs on all other pages (there are hundreds of pages on their site).

Placing these type of embeds should be rule based rather than requiring each node to be edited individually.

**Comment by timurtripp** [comment]
Moved to Site Configuration.
