### ISSUE TITLE
Custom Site Search

### ISSUE THREAD

**Issue by AlanBCole** [CuBoulder/ucb_site_configuration#69]
## Description
I have tried to configure custom site configuration for a newly migrated D10 site. After doing the regular steps (see below) and submitting a search query the site is redirected to the homepage.

## Steps to reproduce
- get custom search id from Google Programmable Search console
- go to `https://www.colorado.edu/summer/admin/config/search/pages` and set up a new search page type of "Google Programmable Search"
- edit this new search page
    - copy the custom search id into the `Google Programmable Search Engine ID` field
    - enter "results" into the `Path` field
    - change the `Query parameter key` field to 'q'
    - save the configuration
- go to `https://www.colorado.edu/summer/admin/config/cu-boulder/general`
    - click on the `advanced` section to open it up
    - under `Enable searching` make sure 'this site' is selected
    - under `site search` enter "/search/results" into the `search page` field
    - save this configuration
- go to the site's homepage and click the magnifying glass icon to open the search modal and enter a search query

## expected behavior

When I search using the magnifying glass icon on the site's homepage I expect to be taken to the site's search/results page with results of the query displayed

## actual behaviour

The page is redirected to the `www.colorado.edu/search/results` and shows no search results.

**Comment by timurtripp** [comment]
The query parameter should be `keys` (not `q`) to work properly. It still doesn't even with the correct query parameter but I've created a PR with the fix.
